name: CFN Deploy (Hub)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Lint CFN templates
        run: |
          pip install cfn-lint
          cfn-lint cloudformation/hub-cfn.yaml cloudformation/spoke-cfn.yaml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: us-east-1

      - name: Create Lambda artifact zip
        run: |
          zip -r lambda.zip lambda -x "**/__pycache__/**"

      - name: Upload artifact to S3
        run: |
          BUCKET=${ARTIFACT_BUCKET:-${{ secrets.ARTIFACT_BUCKET }}}
          : "${BUCKET:?ARTIFACT_BUCKET secret or env must be set}"
          aws s3 cp lambda.zip s3://$BUCKET/ec2-patch/${{ github.sha }}/lambda.zip

      - name: Deploy Hub stack (CFN)
        env:
          PARAMS_FILE: cloudformation/params/dev-hub.json
          ARTIFACT_BUCKET: ${{ secrets.ARTIFACT_BUCKET }}
          EXTERNAL_ID: ${{ secrets.CROSS_ACCOUNT_EXTERNAL_ID }}
        run: |
          # Merge secrets into params dynamically
          jq \
            --arg extId "${EXTERNAL_ID}" \
            --arg bucket "${ARTIFACT_BUCKET}" \
            --arg key "ec2-patch/${{ github.sha }}/lambda.zip" \
            '.CrossAccountExternalId = $extId | .LambdaArtifactBucket = $bucket | .LambdaArtifactKey = $key' \
            "$PARAMS_FILE" > params.effective.json

          PARAMS=$(jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | join(" ")' params.effective.json)

          aws cloudformation deploy \
            --template-file cloudformation/hub-cfn.yaml \
            --stack-name ec2-patch-hub \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --parameter-overrides $PARAMS
