name: Python Tests & CFN Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install -r requirements-dev.txt
          pip install cfn-lint

      - name: CFN lint
        run: |
          cfn-lint cloudformation/hub-cfn.yaml || true
          cfn-lint cloudformation/spoke-cfn.yaml || true

      - name: Run tests
        env:
          PYTHONPATH: ./lambda
        run: |
          pytest -q
